import type { ModelConfigStored, Platform } from "./shared/storage";

export type Severity = "blocker" | "major" | "minor";
export type FindingCategory = "bug" | "typo";

export type ReviewFileHunk = {
  startLineOld: number;
  startLineNew: number;
  heading?: string;
  oldLines: string[];
  newLines: string[];
};

export type ReviewFile = {
  path: string;
  language?: string;
  sizeBytes?: number;
  addedLines?: number;
  removedLines?: number;
  hunks: ReviewFileHunk[];
};

export type ReviewPolicy = {
  skipPatterns: {
    paths: string[];
    names: string[];
    extensions: string[];
    maxFileBytes?: number;
    maxAddedLines?: number;
  };
};

export type ReviewPrMeta = {
  platform: Platform;
  host: string;
  origin: string;
  repo: string;
  number: number;
  branch?: string;
};

export type ReviewRequest = {
  pr: ReviewPrMeta;
  diffFiles: ReviewFile[];
  policy: ReviewPolicy;
  customRules?: string[];
  domainContext?: string[];
  customPrompt?: string;
};

export type ModelFinding = {
  // Internal id, generated by Bello; the LLM does NOT need to send this.
  id: string;
  modelId: string;
  filePath: string;
  // Line range on the selected side of the diff. For single-line issues startLine === endLine.
  startLine: number;
  endLine: number;
  // 'left' = old/base version (L anchors in GitHub diffs), 'right' = new/PR version (R anchors).
  side: "left" | "right";
  category: FindingCategory;
  severity: Severity;
  confidence: number;
  title: string;
  description: string;
  suggestionCode?: string;
  suggestionExplanation?: string;
};

export type ModelTestResult = {
  target: "reviewer" | "arbiter";
  index: number;
  model: string;
  provider: string;
  status: "passed" | "failed";
  error?: string;
  detail?: string;
};

export type MergedFinding = ModelFinding & {
  sourceModels: string[];
  modelVotes: Array<{ modelId: string; severity: Severity; confidence: number }>;
};

export type TokenEstimateBreakdown = {
  promptTokens: number;
  diffTokens: number;
  rulesTokens: number;
  domainTokens: number;
};

export type TokenEstimate = {
  totalTokens: number;
  breakdown: TokenEstimateBreakdown;
  perModel?: Record<string, TokenEstimateBreakdown>;
};

export type TokenUsage = {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
};

export type ReviewVariant = {
  id: string;
  label: string;
  type: "consolidated" | "reviewer" | "arbiter";
  modelId?: string;
  summary: string;
  findings: ModelFinding[];
  error?: string;
};

export type ReviewResult = {
  summary: string;
  findings: MergedFinding[];
  skippedFiles: Array<{ path: string; reason: string }>;
  usageEstimate: TokenEstimate;
  variants?: ReviewVariant[];
};

export type AnalyticsEventPayload = { name: string; params?: Record<string, string | number | boolean> };

export type BgRequest =
  | { type: "ESTIMATE_REVIEW"; payload: ReviewRequest }
  | { type: "RUN_REVIEW"; payload: ReviewRequest }
  | { type: "FETCH_PR_DIFF"; payload: { pr: ReviewRequest["pr"]; paths?: string[]; skip?: ReviewPolicy["skipPatterns"] } }
  | { type: "CANCEL_REVIEW"; payload: { pr: ReviewRequest["pr"] } }
  | { type: "TEST_MODEL"; payload: ModelConfigStored }
  | { type: "TEST_MODEL_SINGLE"; payload: { model: ModelConfigStored["reviewers"][number]; target: ModelTestResult["target"]; index: number } }
  | { type: "GET_LAST_REVIEW"; payload: { pr: ReviewRequest["pr"] } }
  | { type: "TRACK_EVENT"; payload: AnalyticsEventPayload }
  | { type: "PING" };

export type BgResponse =
  | { type: "ESTIMATE_RESULT"; payload: { estimate: TokenEstimate; skippedFiles: { path: string; reason: string }[] } }
  | { type: "DIFF_RESULT"; payload: { files: ReviewFile[]; skippedFiles: { path: string; reason: string }[] } }
  | { type: "REVIEW_PROGRESS"; payload: { stage: "collecting" | "reviewing" | "merging"; progress: number } }
  | { type: "REVIEW_DONE"; payload: ReviewResult }
  | { type: "LAST_REVIEW_RESULT"; payload: ReviewResult }
  | { type: "REVIEW_ERROR"; payload: { message: string } }
  | { type: "TEST_MODEL_RESULT"; payload: { ok: boolean; error?: string; results?: ModelTestResult[] } }
  | { type: "ANALYTICS_OK" }
  | { type: "PONG" }
  | { type: "ERROR"; error: string };

export type SidecarMessage = BgRequest;
